#!/bin/sh

set -e
umask 0002

OPTIONS="--add name --fqdn name --polar disabled --fqdn san-dns --address-addrspec san-mail"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart pki-certificates-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

