#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --fqdn name \
         --show-flags disabled,status --show-table name,filter-dns,filter-mail,filter-ca-cert \
	 --flag X --polar disabled \
         --flag 🔒 --flag-description certificate --flag-match Certificate \
	 --flag 🔑 --flag-description key --flag-match Key \
	 --systemd-parameter StatusText --systemd-prefix pki-certificate@ --systemd-service status \
	 --fqdn filter-dns \
         --address-addrspec filter-mail \
         --default any --symlink-base /usr/share/device/system/pki/certificates/filter-purpose/ --symlink filter-purpose \
         --required \
         --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink filter-ca-cert"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

