#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --fqdn name --show-flags disabled --show-table name,filter-dns,filter-mail,filter-ca-cert --flag X --polar disabled --fqdn filter-dns --address-addrspec filter-mail --required --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink filter-ca-cert"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

