#!/bin/sh

#
# PKI Certificates Autodiscovery
# ==============================
#
# This script autogenerates the pki certificates config.

set -e
umask 0077


systemd-notify --ready


#
# Add/remove pki certificates

find /etc/device/system/pki/certificates/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  target=$(readlink -f "$line")

  if test ! -f "$line/name.txt"; then
    continue;
  fi
  instance="$(head $line/name.txt)"
  uuid=$(basename $target)

  # remove old instances
  if test -f "$line/.removed"; then

    logger -t pki-certificates-autodiscovery "removing pki certificate ${instance} (${uuid})..."

    systemctl disable "pki-certificate@${uuid}"
    systemctl stop "pki-certificate@${uuid}"

    logger -t pki-certificates-autodiscovery "removed pki certificate ${instance} (${uuid})."

    # remove folder
    rm -f "${target}"/*
    rmdir "${target}"
    rm -f "${line}"

  # add new instances
  elif test -f "$line/.added"; then

    logger -t pki-certificates-autodiscovery "creating pki certificate ${instance} (${uuid})..."

    if test -f "$line/disabled.polar"; then

      systemctl disable "pki-certificate@${uuid}"
      systemctl stop "pki-certificate@${uuid}"

    else

      systemctl enable "pki-certificate@${uuid}"
      systemctl start "pki-certificate@${uuid}"

    fi

    logger -t pki-certificates-autodiscovery "created pki certificate ${uuid}."

    rm -f "$line/.added"

  # update instances
  elif test -f "$line/.updated"; then

    logger -t pki-certificates-autodiscovery "updating pki certificate ${uuid} (${uuid})..."

    if test -f "$line/disabled.polar"; then

      systemctl disable "pki-certificate@${uuid}"
      systemctl stop "pki-certificate@${uuid}"

    else

      systemctl enable "pki-certificate@${uuid}"
      systemctl reload-or-restart "pki-certificate@${uuid}"

    fi

    logger -t pki-certificates-autodiscovery "updated pki certificate ${instance} (${uuid})."

    rm -f "$line/.updated"

  fi

done


